camptocamp/devops-stack

Makefile
argocd/argocd/Chart.yaml

This reverts commit c9d869f38928e3a19e69295367d90a39e72ed262.

Revert "Upgrade ArgoCD to 1.7.6"

---

antora-playbook.yml
docs/antora.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/CHANGELOG.adoc
docs/modules/ROOT/pages/access_alertmanager_dashboard.adoc
docs/modules/ROOT/pages/access_argocd_webui.adoc
docs/modules/ROOT/pages/access_grafana_dashboard.adoc
docs/modules/ROOT/pages/access_kubernetes_api.adoc
docs/modules/ROOT/pages/access_prometheus_dashboard.adoc
docs/modules/ROOT/pages/access_traefik_dashboard.adoc
docs/modules/ROOT/pages/deployment.adoc
docs/modules/ROOT/pages/index.adoc
docs/modules/ROOT/pages/provisioning.adoc
docs/modules/ROOT/pages/run.adoc
docs/modules/ROOT/pages/why_automated_sync.adoc
docs/modules/ROOT/pages/why_k3s.adoc
docs/modules/ROOT/pages/why_terraform.adoc

Try to match as much as possible with recommendations made on https://documentation.divio.com/ on the way to structure a documentation.

Change of structure to match https://documentation.divio.com/ recommendations

---

terraform/main.tf

This is required for CSI driver to work.

Mount /var/lib/kubelet with propagation

---

scripts/deploy.sh

Wait for argocd-repo-server before deploying the app of apps

---

.github/workflows/test.yml
Makefile
scripts/pre-clean.sh

Remove all pods before cleanup to release volumes mounted with rshared propagation

---

Makefile
scripts/configure-vault.sh
scripts/destroy-vault.sh
scripts/destroy.sh
scripts/provision.sh

Reverts camptocamp/camptocamp-devops-stack#126

Revert "Don't mount local ~/.terraformrc"

---

.github/workflows/pull-request.yml
.github/workflows/push.yml
.gitignore
tests/k3s-docker-demo-app/Makefile
tests/k3s-docker-demo-app/argocd/demo-app/.helmignore
tests/k3s-docker-demo-app/argocd/demo-app/Chart.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/NOTES.txt
tests/k3s-docker-demo-app/argocd/demo-app/templates/_helpers.tpl
tests/k3s-docker-demo-app/argocd/demo-app/templates/deployment.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/hpa.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/ingress.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/secretproviderclass.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/service.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/serviceaccount.yaml
tests/k3s-docker-demo-app/argocd/demo-app/templates/tests/test-connection.yaml
tests/k3s-docker-demo-app/argocd/demo-app/values.yaml
tests/k3s-docker-demo-app/argocd/project-apps/Chart.yaml
tests/k3s-docker-demo-app/argocd/project-apps/templates/demo-app.yaml
tests/k3s-docker-demo-app/argocd/project-apps/values.yaml
tests/k3s-docker-demo-app/terraform/main.tf
tests/k3s-docker-demo-app/terraform/variables.tf

Create tests and use it for CI instead of examples

---

examples/eks-aws/terraform/main.tf
modules/eks-aws/main.tf
modules/eks-aws/variables.tf

Replace cognito_user_pool_domain resource with module argument

---

docs/modules/ROOT/pages/access_kubernetes_api.adoc
docs/modules/ROOT/pages/access_traefik_dashboard.adoc
docs/modules/ROOT/pages/access_vault_ui.adoc
docs/modules/ROOT/pages/how_to_write_doc.adoc
docs/modules/ROOT/pages/run.adoc

Remove all dollar signs in beginning of lines to make copy/paste easier

---

scripts/app-diff.sh
scripts/destroy.sh
scripts/plan.sh
scripts/provision.sh
scripts/wait-for-app-of-apps.sh

It looks like gitlab-ci does not honor shebang arguments.

Explicitly use "set" directive in shell scripts

---

scripts/destroy.sh

Don't use terraform workspace select with TF_WORKSPACE env var

---

modules/aks-azure/main.tf
modules/argocd-helm/local.tf
modules/argocd-helm/main.tf
modules/argocd-helm/variables.tf
modules/eks-aws/main.tf
modules/k3os-libvirt/main.tf
modules/k3s-docker/main.tf

Use local variables to process default values in complex variables in order to make fields optional.

Better default processing of object variables

---

argocd/app-of-apps/values.tmpl.yaml
modules/argocd-helm/local.tf
modules/argocd-helm/main.tf
modules/argocd-helm/variables.tf

This allows to set domains for each application.
Depends on #377

Allow to set app domains

---

argocd/app-of-apps/templates/apps.yaml
argocd/apps/templates/apps.yaml

This prevents pruning Applications on Merge Request

Prune app of apps only when syncPolicy is set

---

docs/modules/ROOT/pages/run.adoc

- make command failed with https:// git repo URL

change git repo URL so ssh

---

argocd/app-of-apps/values.tmpl.yaml

Adding annotations to ingresses to deployed app are redirected to https

Adding redirect to ssl target

---

.gitlab-ci/pipeline.yaml
examples/eks-aws/.github/workflows/terraform.yml
modules/eks/aws/main.tf

This reverts commit 11024df216094fd6330c987eff030e87b7f3cba0.

Use aws-iam-authenticator instead of the temporary token

---

modules/argocd-helm/main.tf

This is not required anymore as we know the value of the server secretkey.

Don't lookup ArgoCD's server secretkey to generate JWT token

---

modules/argocd-helm/main.tf

Bash is not available in terraform image.

Don't depend on bash-ism

---

modules/aks/azure/main.tf

This is a relic from an old copy/paste

Don't use terraform.workspace variable in module

---

argocd/app-of-apps/values.tmpl.yaml
argocd/argocd/values.yaml

This will configure ArgoCD's pipeline user sooner.

Configure ArgoCD on install (except metrics)

---

modules/argocd-helm/main.tf

This is required for OpenShift 4.

Don't use plaintext to connect to ArgoCD if not in insecure mode

---

argocd/keycloak/templates/keycloakuser.yaml

Add account.manage-account client role to Keycloak admin user

---

argocd/app-of-apps/values.tmpl.yaml
argocd/apps/templates/local-path-provisioner.yaml

https://github.com/k3s-io/k3s/blob/master/manifests/local-storage.yaml

Add local-path-provisioner app

---

modules/argocd-helm/main.tf

Fix passing ArgoCD server secretkey

---

modules/argocd-helm/outputs.tf
modules/outputs.tf

This is required with Terraform v0.15.0

Mark app_of_apps_values output as sensitive

---

argocd/argocd/values.yaml

Co-authored-by: Federico Sismondi <17126766+fsismondi@users.noreply.github.com>

Fix oidc certificate issue for argocd - k3s

---

.github/scripts/app-diff.sh
.github/workflows/terraform.yml

Don't clone repo in integration tests

---

modules/k3s/main.tf
modules/k3s/variables.tf

[k3s] Allow to override base_domain

---

modules/k3s/docker/main.tf
modules/k3s/docker/variables.tf
modules/k3s/docker/versions.tf

Allow publish ports

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/howtos/quickstart_ocp_ipi.adoc
docs/modules/ROOT/pages/howtos/quickstart_ocp_ipi_aws.adoc
docs/modules/ROOT/partials/getting_started.adoc
docs/modules/ROOT/partials/inspect_apps_ocp.adoc
docs/modules/ROOT/partials/ocp_ipi_instant_intro.adoc
docs/modules/ROOT/partials/ocp_kubeconfig.adoc
docs/modules/ROOT/partials/pipeline_outputs_ocp.adoc
examples/ocp-ipi-aws/terraform/install-config.yaml
examples/ocp-ipi-aws/terraform/main.tf
examples/ocp-ipi-aws/terraform/outputs.tf

Adding OCP documentation for IPI installation
Adding example for OCP IPI on AWS

Adding OCP doc

---

modules/argocd-helm/main.tf

If for some reason, the wait for app of apps never succeed and terraform
is run in a CI, the state may not be pushed if the job reaches the CI
timeout.

Add timeout on wait for app of apps

---

docs/modules/ROOT/pages/references/applications/aad-pod-identity.adoc
docs/modules/ROOT/pages/references/terraform_modules/aks/azure.adoc

Adoc update

---

modules/eks/aws/main.tf

This regression was introduced by https://github.com/camptocamp/devops-stack/pull/701

fix(eks): pass missing arg to function

---

modules/sks/exoscale/main.tf

fix(sks): pass down missing variables to argocd-helm

---

modules/sks/exoscale/main.tf
modules/sks/exoscale/values.tmpl.yaml

feat(sks): use letsencrypt-prod when there is more than 1 node pool

---

docs/modules/ROOT/pages/howtos/quickstart_aks.adoc
docs/modules/ROOT/pages/howtos/quickstart_eks.adoc
docs/modules/ROOT/partials/pipelines_gitlab.adoc

chore(docs): update version in Terraform module call

---

docs/modules/ROOT/pages/howtos/filebeat_logging.adoc

docs(filebeat): use example adresses in howto

---

docs/modules/ROOT/pages/references/applications/traefik.adoc
docs/modules/ROOT/pages/references/terraform_modules/aks/azure.adoc
docs/modules/ROOT/pages/references/terraform_modules/sks/exoscale.adoc
modules/sks/exoscale/variables.tf

As per https://changelog.exoscale.com/en/support-of-kubernetes---3

chore(sks): update default Kubernetes version to 1.21.5

---

docs/modules/ROOT/pages/references/terraform_modules/eks/aws.adoc
modules/eks/aws/variables.tf

chore(eks): update Kubernetes version to 1.21

---

docs/modules/ROOT/pages/references/applications/traefik.adoc
docs/modules/ROOT/pages/references/terraform_modules/aks/azure.adoc
modules/aks/azure/variables.tf

Last non-preview supported version

chore(aks): update Kubernetes version to 1.21.2

---

modules/sks/exoscale/variables.tf

chore(sks): update default kubernetes version to 1.21.6

---

.github/workflows/website.yml

fix(website): build website on release published

---

.github/workflows/website.yml

fix(website): build on published

---

.github/workflows/website.yml

fix(website): build on released

---

modules/eks/aws/lb.tf
modules/eks/aws/variables.tf

feat(eks): add extra_lb_target_groups and extra_lb_http_tcp_listeners variables

---

modules/aks/azure/main.tf

Authorization code flow is preferred to implicit code flow since it allows authenticating the resource owner and obtaining explicit authorization to issue an access token.

fix(azure): disable implicit grant for OAuth2 clients

---

modules/sks/exoscale/main.tf

I added a default dns domain ressource and a wildcard dns record one to avoid cert-manager issues on blue/green deployment.
@raphink

feat(sks): add default dns domain and record

---

modules/aks/azure/main.tf
modules/cce/opentelekomcloud/main.tf
modules/eks/aws/main.tf
modules/k3s/main.tf
modules/kind/kind/main.tf
modules/openshift4/aws/main.tf
modules/sks/exoscale/main.tf
modules/values.tmpl.yaml
modules/variables.tf

Patch: allows adding Prometheus OAuth2 proxy extra args and changing proxy's image.

feat: allow changing prometheus oauth2 proxy args

---

modules/values.tmpl.yaml

fix(prometheus): cannot sync issue

---

argocd/csi-secrets-store-provider-azure/Chart.yaml

Co-authored-by: Jérémy Barascut <jeremy.barascut@camptocamp.com>

fix(csi-secrets-store-azure): repo url

---

antora-playbook.yml
docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/tutorials/deploy_sks.adoc

This PR adds the MinIO module as well as some new versions for modules that have jumped up to v2.
There is no need to force a new release on this repository, since there were no modifications on the pages of the main documentation.

docs: add MinIO module and new versions

---

.github/workflows/pr-issues-project.yaml

This PR adds the needed interface to receive secrets from the caller workflows.

ci: add the interface to pass secrets to the ci form caller workflows

---

.github/workflows/publish-antora-docs.yaml
examples/kind/main.tf

This PR fixes a typo on the workflow fix from the previous PR.
I also took the opportunity to integrate the new version of Traefik into the KinD example (depends on [this PR](https://github.com/camptocamp/devops-stack-module-traefik/pull/41)).

ISDEVOPS-98-fix-ci-and-traefik-version

---

examples/eks/main.tf

Hard-code modules to the latest current versions and remove the grafana module.

feat(examples/eks): set modules versions and remove grafana module

---

.github/workflows/modules-terraform-docs.yaml

Fixes a small error on the description on one of the workflows.

ci: fix quotation marks on description

---

.github/workflows/modules-chart-upgrade.yaml

Fixes the matrix generation for the Helm chart dependency upgrade.

ci: fix the chart upgrade workflow

---

antora-playbook.yml

Removes modules that have been deprecated from the documentation, as it was decided in the weekly.

docs: remove deprecated modules from the documentation

---

.github/workflows/modules-chart-update.yaml
docs/modules/ROOT/nav.adoc

- Fixes the PR message for breaking changes.
- Fixes navigation link on the sidebar to the SKS tutorial.

fix/ci: fix some typos on the documentation and on the CI

---

antora-playbook.yml

This PR adds the Metrics Server module to the documentation.

docs: update antora-playbook.yml

---

examples/aks/apps.tf
examples/aks/dns.tf
examples/aks/locals.tf
examples/aks/main.tf
examples/aks/oidc.tf
examples/eks/apps.tf
examples/eks/csi_drivers.tf
examples/eks/locals.tf
examples/eks/main.tf
examples/kind/apps.tf
examples/kind/locals.tf
examples/kind/main.tf
examples/kind/terraform.tf
examples/sks/apps.tf
examples/sks/dns.tf
examples/sks/locals.tf
examples/sks/main.tf
examples/sks/terraform.tf

This PR brings all the available examples up-to-date with the latest releases of the modules of the DevOps Stack.
:warning: **Do a _Rebase and merge_.**

docs: update examples

---

examples/eks/main.tf

Just a new comment for helping people to find AMI Type for x86 VMs

feat: document the ami type for x86 VMs
