antora-playbook.yml
Previous uploaded version was using a github url to get the sources from, where it is not needed, since we're building the documentation site for this project. Better use local directory as a content source
=> Use local directory for project's reference instead of github link

.github/workflows/antoradoc.yml, docs/modules/ROOT/pages/CHANGELOG.adoc
[#124] Don't build and deploy the documentation on PR to master, since useless and might cause issues
=> [#124] Don't build and deploy the documentation on PR to master, since useless and might cause issues

docs/modules/ROOT/pages/CHANGELOG.adoc, docs/modules/ROOT/pages/how_to_write_doc.adoc
[#107] Add link to AsciiDoc Syntax Quick Reference on top of Asciidoc Cheatsheet
I originally added this link in the first branch but lost it before pushing it, re-adding it now.
=> [#107] Add link to AsciiDoc Syntax Quick Reference on top of Asciidoc Cheatsheet

.github/workflows/antoradoc.yml
Upgrade version of actions/setup-node to 1.4.4, replace version by node-version
=> Correct deprecation warning during Antora build

modules/eks-aws/cognito.tf, modules/eks-aws/main.tf, modules/eks-aws/values.tmpl.yaml
This uses Cognito to add OAuth to Grafana.
Ideally, we should be able to forward the OAuth token to Prometheus, but it doesn't seem to work in my tests at the moment. I don't know if it's due to oauth2_proxy.
=> Add OAuth to Grafana

argocd/app-of-apps/values.tmpl.yaml, modules/aks-azure/main.tf, modules/aks-azure/outputs.tf, modules/argocd-helm/main.tf, modules/argocd-helm/outputs.tf, modules/argocd-helm/variables.tf, modules/eks-aws/main.tf, modules/eks-aws/outputs.tf, modules/k3os-libvirt/main.tf, modules/k3os-libvirt/outputs.tf, modules/k3s-docker/main.tf, modules/k3s-docker/outputs.tf
This puts the app of apps helm release inside the argocd-helm module, and refactors the variables for more clarity.
It supersedes #340
=> Instantiate the app of apps inside the argocd-helm module

modules/argocd-helm/main.tf
This is mandatory with slow internet connections
=> Increase argocd helm release timeout

tests/k3s-libvirt/terraform/main.tf
The memory for the server is set by default to 2048Mb but it isn't enough for the whole stack. This is why I suggest to extend it to 8Gb. Intermediate stage 4Gb doesn't offer enough stability and many pods are crashing due to OOM
=> Extending default memory to 8Gb for better stability

argocd/app-of-apps/values.tmpl.yaml, modules/aks/azure/main.tf, modules/argocd-helm/main.tf, modules/argocd-helm/variables.tf, modules/eks/aws/main.tf, modules/k3s/main.tf, modules/variables.tf
This is useful when you want your ArgoCD token to still be valid on
redeploy.
=> Allow to pass ArgoCD's Server SecretKey

argocd/app-of-apps/values.tmpl.yaml, modules/argocd-helm/local.tf, modules/argocd-helm/main.tf, modules/argocd-helm/variables.tf
For the future integration of OCP4, we need to be able to enable/disable basic Kubernetes components as they're already available in OCP (such as ingress controller, prometheus etc)
=> Making components to be enabled or not

.gitlab-ci/pipeline.yaml, docs/modules/ROOT/pages/howtos/quickstart_aks.adoc, docs/modules/ROOT/pages/howtos/quickstart_eks.adoc, examples/eks-aws/.github/workflows/terraform.yml, examples/eks-aws/terraform/main.tf, examples/k3s-docker-demo-app/terraform/main.tf, examples/k3s-libvirt-demo-app/terraform/main.tf, tests/k3s-docker/terraform/main.tf, tests/k3s-libvirt/terraform/main.tf
Now that almost everything is done in Terraform, we don't depend on Terraform workspaces anymore (of course we can still use it, but we don't depend on it).
This simplifies a bit the process as we don't have to explain how Terraform workspaces works and allows the DevOps Stack to be deployed with a single git repository instead of one for statefull resources and one for stateless resources.
=> Don't depend on Terraform workspaces

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/howtos/quickstart_aks.adoc, docs/modules/ROOT/pages/howtos/quickstart_eks.adoc, docs/modules/ROOT/pages/howtos/quickstart_k3s_docker.adoc, docs/modules/ROOT/pages/howtos/quickstart_k3s_libvirt.adoc, docs/modules/ROOT/pages/references/terraform_modules/aks_azure-header.adoc, docs/modules/ROOT/pages/references/terraform_modules/aks_azure.adoc, docs/modules/ROOT/pages/references/terraform_modules/argocd-helm-header.adoc, docs/modules/ROOT/pages/references/terraform_modules/argocd-helm.adoc, docs/modules/ROOT/pages/references/terraform_modules/eks_aws-header.adoc, docs/modules/ROOT/pages/references/terraform_modules/eks_aws.adoc, docs/modules/ROOT/pages/references/terraform_modules/k3s_docker-header.adoc, docs/modules/ROOT/pages/references/terraform_modules/k3s_docker.adoc, docs/modules/ROOT/pages/references/terraform_modules/k3s_libvirt-header.adoc, docs/modules/ROOT/pages/references/terraform_modules/k3s_libvirt.adoc, docs/modules/ROOT/pages/references/terraform_modules/openshift4_aws-header.adoc, docs/modules/ROOT/pages/references/terraform_modules/openshift4_aws.adoc
This uses https://github.com/terraform-docs/terraform-docs/ to generate reference docs for Terraform modules.
Rendered on https://raphink.devops-stack.io/docs/devops-stack/latest/references/terraform_modules/argocd-helm.html
=> Add Terraform module references

modules/main.tf
Somehow Terraform fails with:
```
The "count" value depends on resource attributes that cannot be determined
155until apply, so Terraform cannot predict how many instances will be created.
156To work around this, use the -target argument to first apply only the
157resources that the count depends on.
```
We need some unit tests to check this...
=> Fix passing Grafana admin password

modules/k3s/docker/main.tf
Note: the integration test failure on update is "normal" because of the change in the way the module manages the kubeconfig file.
The new version of the module should improve this.
=> Upgrade camptocamp/k3s/docker to 0.10.1

.gitignore, modules/k3s/docker/main.tf, modules/k3s/docker/variables.tf, modules/k3s/docker/versions.tf
Adding new variable to suport server_port and base_domain for the new version of the k3s/docker module.
=> Allow to override cluster endpoint

modules/eks/aws/cert-manager.tf, modules/eks/aws/lb.tf, modules/eks/aws/loki.tf, modules/eks/aws/main.tf, modules/eks/aws/versions.tf
We definitely need integration tests on EKS and AKS...
=> Upgrade AWS modules to work with Terraform 0.15

.gitlab-ci/pipeline.yaml
This avoid running multiple Terraform jobs at the same time.
=> Use resource group in Gitlab CI pipeline

modules/values.tmpl.yaml
Without this patch it generates this:
```yaml
project: default
source:
repoURL: 'https://github.com/camptocamp/devops-stack.git'
path: argocd/csi-secrets-store-provider-azure
targetRevision: v0.31.0
helm:
values: |
csi-secrets-store-provider-azure:
null
destination:
server: 'https://kubernetes.default.svc'
namespace: csi-secrets-store-provider-azure
syncPolicy:
automated:
prune: true
selfHeal: true
```
Which is incorrect because of `null`.
=> Fix csi-secrets-store-provider-azure deployment

modules/eks/aws/main.tf
Using conditional result to set the `worker_groups` requires to have on both sides the same result type. The first part of the current implementation will produce a `tuple` and the second part will produce a `list`. When declaring multiple worker groups, Terraform will return a well-know error: https://github.com/hashicorp/terraform/issues/22405.
To avoid that, this PR removes the conditional results and replaces it by a `concat()` and a `try()`. The `try()` will render the extra worker groups if there is any or return an empty array. The `concat()` will merge the first worker group with the extra ones.
=> eks/aws: fix multiple worker groups support

modules/aks/azure/outputs.tf
Azure needs the cluster id if we want to create a group that can connect to the AKS. We can then create better RBAC for This cluster.
For instance, as we cannot remove StorageClasses, one solution would be to make them invisible for the users.
=> feat: output clusterid. This is used for group management

modules/k3s/main.tf, modules/k3s/values.tmpl.yaml
This is a non-production implementation (single-tenant mode and no SSL
verification) to deploy Loki depending only on a S3-compatible APIs storage solution.
It is based on the following configuration example:
https://grafana.com/docs/loki/latest/configuration/examples/#s3-compatible-apis
=> feat(k3s): use minio as unique storage solution for Loki

argocd/apps/templates/extra-app-projects.yaml
This is required because AppProjects' Roles' Tokens are stored in
status.
=> feat: allow to set AppProject's status

argocd/argocd/values.yaml, modules/argocd-helm/main.tf, modules/values.tmpl.yaml
The volume "certificate" is created only when keycloak is enabled and cert-manager is configured as ca-issuer.
The volume isn't needed otherwise, and declaring it might block ArgoCD's deployment since the secret "argocd-tls" might not exist.
=> fix: argocd secret dependency

modules/argocd-helm/main.tf, modules/argocd-helm/outputs.tf, modules/argocd-helm/variables.tf, modules/outputs.tf, modules/variables.tf
We should pass the SSH private key to the DevOps Stack instead of
generating it because in case of blue/green scenario, we don't want to
have to redeploy the deploy key.
=> fix: deploy keys should not be tight to the DevOps Stack

argocd/aad-pod-identity/values.yaml
Co-authored-by: madridi <mohamed-amine.dridi@camptocamp.com>
=> fix: dropping aad-pod-identity's deprecated forceNameSpaced in favour of new forceNamespaced

modules/aks/azure/versions.tf, modules/argocd-helm/versions.tf, modules/eks/aws/versions.tf, modules/k3s/docker/versions.tf, modules/k3s/libvirt/versions.tf
It's currently not possible to instantiate 2 different versions of the DevOps Stack in the same namespace if one of the versions of the providers differs. Which would be convenient in case of blue/green scenario to upgrade to a newer version of the DevOps Stack.
=> feat: use loose dependencies in Terraform modules

modules/k3s/docker/main.tf
Somehow, cluster destruction with k3s module sometimes fails or takes a
while (probably due to node draining). This have an impact on
development and testing cases.
Newer version of k3s/docker module have a fix for that.
=> fix: upgrade k3s/docker module

modules/k3s/docker/main.tf
Registry mirrors in k3s/docker variant are useful for development on
slow connections. As some images are hosted on https://ghcr.io, we
should also mirror this one.
=> feat(k3s-docker): add registry mirror for ghcr.io

argocd/kube-prometheus-stack/Chart.yaml, modules/values.tmpl.yaml
We don't have to set `pathType` to `ImplementationSpecific` anymore in
Prometheus's Ingress configuration, has it as been set as default.
=> feat(kube-prometheus-stack): upgrade to v18.0.0

argocd/aad-pod-identity/templates/namespace.yaml, argocd/cert-manager/templates/namespace.yaml, argocd/csi-secrets-store-provider-azure/templates/namespace.yaml, argocd/efs-provisioner/templates/namespace.yaml, argocd/kube-prometheus-stack/templates/namespace.yaml, argocd/loki-stack/templates/namespace.yaml, argocd/minio/templates/namespace.yaml, argocd/secrets-store-csi-driver/templates/namespace.yaml, argocd/thanos/templates/namespace.yaml, argocd/traefik/templates/namespace.yaml, modules/values.tmpl.yaml
In order to not have to declare all DevOps Stack Applications' namespace
explicitely, we should allow implicit namespace creation.
=> feat: set CreateNamespace=true syncOption

argocd/aad-pod-identity/templates/namespace.yaml
When creating AzureIdentities and AzureIdentityBindings, Namespaces must
exist. This patch create the Namespaces.
=> feat(aad-pod-identity): create identities Namespaces

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/howtos/continuous_delivery_gitflow_workflow.adoc
@Vampouille , @modridi , @vquiby  here the doc we discussed today 
some re-working items that were suggested:
=> docs: add  howtos

modules/sks/exoscale/variables.tf
```
╷
│ Error: Post "https://api-de-fra-1.exoscale.com/v2.alpha/sks-cluster": invalid request: Invalid Kubernetes version 1.20.9. Available versions are: 1.22.1, 1.21.4
│ 
│   with module.cluster.module.cluster.exoscale_sks_cluster.this,
│   on .terraform/modules/cluster.cluster/main.tf line 1, in resource "exoscale_sks_cluster" "this":
│    1: resource "exoscale_sks_cluster" "this" {
│ 
╵
```
=> feat(sks): use Kubernetes 1.21.4 by default

modules/aks/azure/main.tf, modules/aks/azure/variables.tf
Using an `azurerm_kubernetes_cluster_node_pool` resource is one way to do it.
There is a PR in the azure/aks module that's been sitting there for a while (https://github.com/Azure/terraform-azurerm-aks/pull/89).
Note: this configuration supports only a subset of the arguments that can be set in the `azurerm_kubernetes_cluster_node_pool` resource.
The following is an sample variable to pass to the devops stack azure module:
```
node_pools = {
dev = {
vm_size     = "Standard_DS2_v2"
node_count  = 1
node_taints = ["env=dev:NoExecute", "env=dev:NoSchedule"]
}
}
```
=> feat(aks): add support for node pools in AKS

modules/aks/azure/main.tf
add node label param, so we can use podnodeselector admission controller for scheduling pods to specific nodes
add mode param, so we can support user/system separation at a node pool level
=> feat(aks): extend accepted params for node pools

modules/eks/aws/lb.tf
A bug was sending all incoming traffic on the NLB to the port 443 on the
cluster, whether it was http or https. This seems to have been working
anyway in most cases because traefik is able to receive ssl and non-ssl on
the same port.
This commit fixes this behavior and sends incomming http traffic to the port
80 on the cluster. This change might break custom (but bad) ingress
configurations that would expect all traffic to come on port 443.
=> fix(eks)!: send http traffic on NLB to port 80 on cluster

docs/modules/ROOT/pages/references/terraform_modules/k3s/docker.adoc, modules/k3s/docker/variables.tf
=> chore(k3s): update default Kubernetes version to 1.21

docs/modules/ROOT/pages/howtos/quickstart_kind.adoc, docs/modules/ROOT/pages/references/applications/traefik.adoc, docs/modules/ROOT/pages/references/terraform_modules/aks/azure.adoc, site/data/en/homepage.yml
=> docs(kind): add docs for Kind

argocd/argocd/Chart.yaml
Upgrade to ArgoCD Helm chart version that includes https://github.com/argoproj/argo-helm/pull/1018 (Fix following the github SSH key fingerprint update).
=> chore: upgrade argocd

Makefile, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/references/applications/argocd.adoc, docs/modules/ROOT/pages/references/terraform_modules/k3s/docker.adoc, docs/modules/ROOT/pages/references/terraform_modules/kind/kind.adoc, modules/kind/kind/README.adoc
=> feat(docs): improve KinD docs

argocd/traefik/templates/redirection-middleware.yaml, modules/values.tmpl.yaml
OAuth workflow fails for URLs without cluster name even when these are declared in the application's reply URLs.
One solution is to do a permanent redirection to the URLs with cluster names and proceed with OAuth from there.
This PR implements the redirection and affects the following components:
- Alertmanager
- Argocd
- Grafana
- Prometheus
=> feat: use url without cluster name

modules/aks/azure/main.tf
This PR fixes (#802) where a wrong resource app id is passed.
If an azuread application was created by the devops stack, it will be updated in-place upon devops stack version upgrade.
=> fix(aks): azuread application use ms graph

modules/sks/exoscale/outputs.tf
We need to access `local.kubernetes` in order to provision the kubernetes provider without needing the kubeconfig which require a local_file resource and create divergences during the plan due to the kubeconfig output.
=> feat(sks): expose local.kubernetes to outputs

modules/aks/azure/main.tf
Get cluster name dynamically from cluster module outputs.
This allows modifying the cluster without breaking the data source.
=> fix(aks): use soft dependency between cluster and data source

tests/eks-aws/main.tf
By default, only public access is enabled. Be explicit by enabling both.
=> feat(eks): enable cluster private access

modules/aks/azure/variables.tf
* orchestrator version of nodes default is now v1.21.9, v1.21.2 was dropped by Azure
=> fix(aks): bump default ochestration version for nodes

modules/sks/exoscale/main.tf
I updated the camptocamp' sks module to add support for labels and taints on nodepool ressources, this PR just bump the camptocamp/sks/exoscale version used to 0.4.0.
=> feat(sks): update camptocamp's exoscale sks module to 0.4.0

argocd/keycloak/templates/ingress.yaml
The keycloak ingress template is incompatible with versions of k8s >= 1.22.
Furthermore, it's a blocking issue on Exoscale since SKS can be created with k8s 1.22 or 1.23 only. This PR solve this.
=> fix(keycloak): invalid ingress ressource on v1beta1 api on k8s >= 1.22

modules/sks/exoscale/main.tf
On the SKS module, all optional fields to define nodepools could not be used due to a type mismatch between `default_nodepool` and `var.nodepools` in the `coalesce` function call. 
This PR solve this but however it's now mandatory to have all fields defined even those not used (set on `null`) on nodepool creation. For exemple:
```hcl
nodepools = {
"is-internal-green" = {
size            = 2
instance_type   = "standard.large"
description     = "Default nodepool for is-internal"
instance_prefix = null
disk_size       = null
labels              = null
taints              = null
private_network_ids = null
}
}
```
=> fix(sks): type mismatch into coalesce call for nodepools definitions

argocd/cert-manager/Chart.yaml, argocd/cert-manager/templates/clusterissuer.yaml
Same core problem as #890, since Exoscale doesn't allow to create sks services with others version than **1.22.8** or **1.23.5**, some components aren't compatible anymore like this is the case for cert-manager.
This PR update the chart to **v1.8.0** to solve this and also update cluster issuer templates to make them compatible with the new api version of cert-manager.
=> fix(cert-manager): incompatibility with k8s >= 1.22

docs/modules/ROOT/pages/howtos/quickstart_k3s_libvirt.adoc, modules/k3s/libvirt/versions.tf
This new version fixes the problem that required in the past a manual
installation in a specific location. The documentation is also corrected
accordingly
=> chore: upgrade libvirt provider to v0.6.12

argocd/traefik/templates/dashboard.yaml, modules/values.tmpl.yaml
It doesn't seem relevant to me to force the deployment of an ingress to access the traefik dashboard as well as an additional container for the auth (using a weird image not even maintained instead of a classic oauth2-proxy like our others apps, why?) when a simple port-forward is possible to access it when needed.
Additionally, the dashboard isn't even accessible on my side out-of-the-box.
With this PR, I allow the deactivation of this feature.
=> feat(traefik): allow disabling of dashboard's ingress and auth

.github/workflows/modules-terraform-docs.yaml
This is needed so that the last action on the workflow can be successfully executed, although technically the called workflow should already have the permissions (https://docs.github.com/en/actions/using-workflows/reusing-workflows#overview).
=> ci: add explicit permissions to terraform docs workflow

argocd/kube-prometheus-stack/values.yaml, modules/values.tmpl.yaml
Datasource was problematic : if both prometheus and loki were default, only one was available.
As you can only have one default datasource, it is decided that loki should not be the  one. 
This MR simply remove the default status of loki datasrouce. 
This MR as been tested and working.
Signed-off-by: Julien Godin <julien.godin@camptocamp.com>
=> feat: Loki is not the default datasource

.github/workflows/modules-terraform-docs.yaml
This PR finally (*I hope*) fixes the issue with the permissions on the terraform-docs workflow. See [this issue](https://github.com/terraform-docs/gh-actions/issues/90) that finally pointed me in the right direction.
=> ci: fix permissions issue on the tf docs workflow

argocd/csi-secrets-store-provider-azure/Chart.yaml, argocd/loki-stack/Chart.yaml, modules/aks/azure/main.tf, modules/aks/azure/values.tmpl.yaml, modules/aks/azure/variables.tf
Two commits :
* One to permit the management of several domains instead of just one (for certs renewals)
* One to permit to allow the modification of the cert-manager "http01" configuration section
The other two are cherry picked commits from master so that we don't have a diff on the gs platform running on the feature branch.
=> feat(azure): add domains and http01 inputs for cert-manager

argocd/argocd/Chart.yaml, modules/openshift4/aws/values.tmpl.yaml, modules/values.tmpl.yaml
With this PR I updated the ArgoCD's chart to the latest version since it haven't be done in a while and because it's needed to be able to use the [argocd-cmp-helmfile](https://github.com/camptocamp/docker-argocd-cmp-helmfile) plugin (and for the use of sidecar container for plugins in general).
I also changed the `HELM_VALUES` env variable to `ARGOCD_ENV_HELM_VALUES` to fix [this breaking change](https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/2.3-2.4/#update-plugins-to-use-newly-prefixed-environment-variables) in the latest argocd image version (a new `camptocamp/argocd` version was released FYI).
Be aware that few major/breaking changes were introduced in the lot of versions of ArgoCD's chart/image that we have behind so it may have some incompatibilities with some of …
=> feat(argocd): update chart to v5.14.1

.github/workflows/pr-issues-project.yaml, .gitignore
This PR modifies the workflow that adds PRs and Issues to our project board. It adds the ability to authenticate using a GitHub app, which is needed in order to have access to our multiple repositories as well as the centralized project itself.
=> ci: add new workflow to manage PRs and issues on the new project board

examples/kind/main.tf
Traefik module version 1.2.0 doesn't propagate `enable_service_monitor` to root module resulting in an attempt to create the service monitor while CRD isn't yet deployed. 1.2.2 fixes the problem.
=> fix: upgrade traefik to deactivate service monitor

.github/workflows/modules-chart-upgrade.yaml, .github/workflows/modules-terraform-docs.yaml
Today, we currently perform manual upgrades for the public Helm charts we utilize. However, with this PR, we can introduce automation and eliminate the need for manual intervention. The PR includes a workflow  that verifies if there are any newly released versions for the charts. It then generates a pull request containing the latest release. Our only task would be to review the changes and merge them if everything appears satisfactory.
=> ci: add centralized workflow to upgrade charts dependencies on modules

.github/workflows/modules-chart-upgrade.yaml
This PR fixes a problem in the centralized workflow used to upgrade Helm dependencies on the module's charts. GitHub did not like when we pinned the version v0 instead of v0.1.0
=> ci: pin version of the upgrade action

.github/workflows/modules-chart-upgrade.yaml, .github/workflows/modules-release-please.yaml, .github/workflows/release-please.yaml
- The autorelease workflows now will add the release PRs to our project board.
- The Helm dependency autoupgrade workflow is modified to support the latest developments on our [custom GitHub Action](https://github.com/camptocamp/helm-dependency-upgrade-action).
=> ci: modify autoupgrade workflow and improve release workflows

website/layouts/contact/list.html
We replaced the contact form of the DevOps Stack website to a link to our corporate contact page.
=> feat(website): use the camptocamp.com contact page
